env:
  browser: true
  es6: true
  jest: true
extends:
  - 'plugin:react/recommended'
  - 'plugin:react-hooks/recommended'
  - google
  - prettier
  - eslint:recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules: {}
settings:
  react:
    pragma: React
    version: 16.13.1
